type: function_sql
category: transform_array
author:
  name: Paul Marcombes
  url: https://www.linkedin.com/in/paul-marcombes
  avatar_url: "https://lh3.googleusercontent.com/a-/ACB-R5RDf2yxcw1p_IYLCKmiUIScreatDdhG8B83om6Ohw=s260"
description: Return distinct values
arguments:
  - name: arr
    type: any type
output:
  name: distinct_values
  type: any type
examples:
  - description: ""
    arguments:
      - "[1, 4, 3, 4]"
    output: "[1, 4, 3]"
code: array(select distinct value from unnest(arr) as value)
